# This is a basic workflow to help you get started with Actions

name: testing

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5' 
          architecture: 'x64'
      - uses: docker-practice/actions-setup-docker@master
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Running tests
        run: |
          set -x
          docker run -d --rm --hostname arbiter-rabbit --name arbiter-rabbit \
              -p 5672:5672 -e RABBITMQ_DEFAULT_USER=user \
              -e RABBITMQ_DEFAULT_PASS=password \
              -e RABBITMQ_DEFAULT_VHOST=carrier \
              rabbitmq:3-management
          coverage run --source=arbiter -m pytest --verbosity=1 tests/
      - name: Publish report
        run: coverage report -m
